[AIE] Add missing Copyright info
Xilinx/llvm-aie pull request #140
Opened 2024-07-31 07:24 UTC by andcarminati

2024-08-14 11:34 UTC, gbossu approved these changes, later dismissed

2024-08-14 12:08 UTC, ValentijnvdBeek requested changes

2024-08-14 12:08 UTC, ValentijnvdBeek commented on llvm/lib/Target/AIE/AIEInterBlockScheduling.cpp
> +//
These files were committed three months ago, so you should just put 2024 and not 2023-2024.

2024-08-15 07:27 UTC, andcarminati commented on llvm/lib/Target/AIE/AIEInterBlockScheduling.cpp
> +//
Done! Thank you for pointing this detail.

2024-08-15 07:39 UTC, ValentijnvdBeek approved these changes

2024-08-20 14:16 UTC, gbossu approved these changes

2024-08-20 15:25 UTC, merged